#!/usr/bin/env python3

import glob, os
import argparse
from cajparser import CAJParser
from utils import add_outlines

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(help="commands", dest="command")

    show_parser = subparsers.add_parser("show", help="Show the information of the CAJ file.")
    show_parser.add_argument("input", help="Path to the CAJ file.")

    convert_parser = subparsers.add_parser("convert", help="Convert the CAJ file to PDF file.")
    convert_parser.add_argument("input", help="Path to the CAJ file.")
    convert_parser.add_argument("-o", "--output", help="Output path to the PDF file.", required=False)

    convert_parser = subparsers.add_parser("bconvert", help="Convert  a batch of CAJ files to PDF files.")
    convert_parser.add_argument("input", help="Path to the CAJ files folder.")
    convert_parser.add_argument("-o", "--output", help="Output path to the PDF file.", required=False)

    outlines_parser = subparsers.add_parser("outlines", help="Extract outlines from the CAJ file and add it to PDF file.")
    outlines_parser.add_argument("input", help="Path to the CAJ file.")
    outlines_parser.add_argument("-o", "--output", help="Path to the PDF file.", required=True)

    parse_parser = subparsers.add_parser("parse", help="Parse CAJ file for debugging/development")
    parse_parser.add_argument("input", help="Path to the CAJ file.")

    text_extract_parser = subparsers.add_parser("text-extract", help="Parse CAJ file for debugging/development")
    text_extract_parser.add_argument("input", help="Path to the CAJ file.")

    args = parser.parse_args()

    if args.command == "show":
        caj = CAJParser(args.input)
        if caj.format == "PDF" or caj.format == "KDH":
            print("File: {0}\nType: {1}\n".format(args.input, caj.format))
        else:
            print("File: {0}\nType: {1}\nPage count: {2}\nOutlines count: {3}\n".format(
                args.input,
                caj.format,
                caj.page_num,
                caj.toc_num
            ))

    if args.command == "convert":
        caj = CAJParser(args.input)
        if args.output is None:
            if args.input.endswith(".caj"):
                args.output = args.input.replace(".caj", ".pdf")
            elif (len(args.input) > 4 and (args.input[-4] == '.' or args.input[-3] == '.') and not args.input.endswith(".pdf")):
                args.output = os.path.splitext(args.input)[0] + ".pdf"
            else:
                args.output = args.input + ".pdf"
        caj.convert(args.output)
        print("Converted: {0}".format(args.input))

    if args.command == "bconvert":
        caj_files = glob.glob(os.path.join(args.input, "*.caj"))
        for caj_file in caj_files:
            try:
                caj = CAJParser(caj_file)
                if args.output is None:
                    if caj_file.endswith(".caj"):
                        output = caj_file.replace(".caj", ".pdf")
                    elif (len(caj_file) > 4 and (caj_file[-4] == '.' or caj_file[-3] == '.') and not caj_file.endswith(".pdf")):
                        output = os.path.splitext(caj_file)[0] + ".pdf"
                    else:
                        output = caj_file + ".pdf"
                else:
                    if not os.path.exists(args.output):
                        os.makedirs(args.output)
                    output = os.path.join(args.output, os.path.basename(caj_file).replace(".caj", ".pdf"))
                caj.convert(output)
                print("Converted: {0}".format(caj_file))
            except Exception as e:
                print("Error: {0}".format(e))
                continue

    if args.command == "outlines":
        caj = CAJParser(args.input)
        if caj.format == "PDF" or caj.format == "KDH":
            raise SystemExit("Unsupported file type: {0}.".format(caj.format))
        toc = caj.get_toc()
        add_outlines(toc, args.output, "tmp.pdf")
        os.replace("tmp.pdf", args.output)

    if args.command == "text-extract":
        caj = CAJParser(args.input)
        caj.text_extract()

    if args.command == "parse":
        caj = CAJParser(args.input)
        caj.parse()
